package com.ysyx.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAMERA_INFO.
 */
public class CameraInfo {

    private Long id;
    /** Not-null value. */
    private String NAME;
    /** Not-null value. */
    private String STD_ID;
    private String GPS_X;
    private String GPS_Y;
    private String GPS_Z;

    public CameraInfo() {
    }

    public CameraInfo(Long id) {
        this.id = id;
    }

    public CameraInfo(Long id, String NAME, String STD_ID, String GPS_X, String GPS_Y, String GPS_Z) {
        this.id = id;
        this.NAME = NAME;
        this.STD_ID = STD_ID;
        this.GPS_X = GPS_X;
        this.GPS_Y = GPS_Y;
        this.GPS_Z = GPS_Z;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNAME() {
        return NAME;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    /** Not-null value. */
    public String getSTD_ID() {
        return STD_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSTD_ID(String STD_ID) {
        this.STD_ID = STD_ID;
    }

    public String getGPS_X() {
        return GPS_X;
    }

    public void setGPS_X(String GPS_X) {
        this.GPS_X = GPS_X;
    }

    public String getGPS_Y() {
        return GPS_Y;
    }

    public void setGPS_Y(String GPS_Y) {
        this.GPS_Y = GPS_Y;
    }

    public String getGPS_Z() {
        return GPS_Z;
    }

    public void setGPS_Z(String GPS_Z) {
        this.GPS_Z = GPS_Z;
    }

}
