package com.ysyx.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ysyx.greendao.CameraInfo;

import com.ysyx.greendao.CameraInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cameraInfoDaoConfig;

    private final CameraInfoDao cameraInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cameraInfoDaoConfig = daoConfigMap.get(CameraInfoDao.class).clone();
        cameraInfoDaoConfig.initIdentityScope(type);

        cameraInfoDao = new CameraInfoDao(cameraInfoDaoConfig, this);

        registerDao(CameraInfo.class, cameraInfoDao);
    }
    
    public void clear() {
        cameraInfoDaoConfig.getIdentityScope().clear();
    }

    public CameraInfoDao getCameraInfoDao() {
        return cameraInfoDao;
    }

}
